name: Custom Testing
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  Pytest:
    runs-on: ubuntu-latest
    - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Unit Tests
        run: |
          pytest
